# Generated by Django 3.0.4 on 2020-03-14 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HackAttendDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=25)),
                ('fileName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='handleFileRequest.FileStore')),
            ],
        ),
    ]
